services:
  terria:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./wwwroot/config.json:/app/wwwroot/config.json
      - ./wwwroot/dep.json:/app/wwwroot/init/dep.json
      - ./wwwroot/serverconfig.json:/app/wwwroot/serverconfig.json
